CREATE TABLE pagamentos_venda (
                                  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                  pagamento_id BIGINT NOT NULL,
                                  venda_id BIGINT NOT NULL,
                                  valor_pago DOUBLE PRECISION NOT NULL,
                                  atualizado_por VARCHAR(255) NOT NULL,
                                  data_pagamento TIMESTAMP
);