CREATE TABLE pagamentos (
                                   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   venda_id BIGINT NOT NULL,
                                   valor_pago DOUBLE PRECISION NOT NULL,
                                   atualizado_por VARCHAR(255) NOT NULL,
                                   data_pagamento TIMESTAMP
);