CREATE TABLE log_sistema (
                                   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   mensagem VARCHAR(255) NOT NULL,
                                   usuario VARCHAR(255) NOT NULL,
                                   cliente_id BIGINT,
                                   venda_id BIGINT ,
                                   categoria_log VARCHAR(255) NOT NULL,
                                   datahora TIMESTAMP
);