CREATE TABLE vendas (
                        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        cliente_id BIGINT NOT NULL,
                        cliente VARCHAR(255) NOT NULL,
                        vendedor_id BIGINT NOT NULL,
                        valor_total_venda DOUBLE PRECISION NOT NULL,
                        valor_pago DOUBLE PRECISION NOT NULL,
                        status VARCHAR(255) NOT NULL,
                        data_ultimo_pagamento TIMESTAMP,
                        data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);